version: '3.8'

services:
    app:
        container_name: container-ads
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - db
            - cache
        restart: unless-stopped

    db:
        container_name: container-db
        image: mysql
        restart: always
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: more
            MYSQL_DATABASE: advertisements
            MYSQL_USER: richxcame
            MYSQL_PASSWORD: more
        volumes:
            - db_data:/var/lib/mysql
    cache:
        image: redis:alpine
        ports:
            - '6380:6379'

volumes:
    db_data:
